package dbtest

const (
	POSTGRES_USERNAME = "db_user"
	POSTGRES_PASSWORD = "12345"
	POSTGRES_HOST = "192.168.7.73"
	POSTGRES_PORT = "1999"
	POSTGRES_DBNAME = "pgbench"
	POSTGRES_SSLMODE = "disable"
)