package testcase
import (
	
)
var SimpleSql = []string{
"select 1;",
"select 1 + 1;",
"select /*db*/ 1+1;",
"select /*+db+*/1;",
"select 2 + 2;",
"drop table bigtable;",
"create table bigtable(id int, name varchar(1024), age int);",
"insert into bigtable(id, name, age) values(10, 'lisi', 30);",
"insert into bigtable(id, name, age) values(11, 'wangshan1',31);",
"insert into bigtable(id, name, age) values(12, 'wangshan2',32);",
"insert into bigtable(id, name, age) values(13, 'wangshan3',33);",
"insert into bigtable(id, name, age) values(14, 'wangshan4',34);",
"insert into bigtable(id, name, age) values(15, 'wangshan5',35);",
"insert into bigtable(id, name, age) values(16, 'wangshan6',36);",
"insert into bigtable(id, name, age) values(17, 'wangshan7',37);",
"insert into bigtable(id, name, age) values(18, 'wangshan8',38);",
"insert into bigtable(id, name, age) values(19, 'wangshan9',39);",
"insert into bigtable(id, name, age) values(20, 'wangshan10',40);",
"insert into bigtable(id, name, age) values(21, 'wangshan11',41);",
"insert into bigtable(id, name, age) values(22, 'wangshan12',42);",
"insert into bigtable(id, name, age) values(23, 'wangshan13',43);",
"insert into bigtable(id, name, age) values(24, 'wangshan14',44);",
"insert into bigtable(id, name, age) values(25, 'wangshan15',45);",
"insert into bigtable(id, name, age) values(26, 'wangshan16',46);",
"insert into bigtable(id, name, age) values(27, 'wangshan17',47);",
"insert into bigtable(id, name, age) values(28, 'wangshan18',48);",
"insert into bigtable(id, name, age) values(29, 'wangshan19',49);",
"insert into bigtable(id, name, age) values(29, 'wangshan20',50);",
"insert into bigtable(id, name, age) values(29, 'wangshan21',51);",
"select * from bigtable;",
"select * from bigtable_0;",
"select * from bigtable_1;",
"update bigtable set name='lisi' where id=20;",
"update bigtable set name='lisi123' where id = 21;",
"update bigtable_0 set name='lisi' where id = '0';",
"select * from bigtable;",
"select * from bigtable_0;",
"select * from bigtable_1;",
"select id, name , age from bigtable;",
"select id as no, name ,age from bigtable;",
"select id, name as alias, age from bigtable;",
"select id , name, age as secret from bigtable;",
"select max(age) as maxage  from bigtable;",
"select max(age) maxage from bigtable_0;",
"select max(age) from bigtable_1;",
"select min(id) from bigtable;",
"select min(id) from bigtable_0;",
"select min(id) from bigtable_1;",
"select sum(age) from bigtable;",
"select sum(age) from bigtable_0;",
"select sum(age) from bigtable_1;",
"select * from bigtable order by id;",
"select * from bigtable order by age;",
"select * from bigtable_0 order by id;",
"select * from bigtable_1 order by age;",
"select * from bigtable order by id desc;",
"select * from bigtable order by age desc;",
"select * from bigtable_0 order by id desc;",
"select * from bigtable_1 order by age desc;",
"select * from bigtable order by id asc;",
"select * from bigtable order by age asc;",
"select * from bigtable_0 order by id asc;",
"select * from bigtable_1 order by age asc;",
"select distinct id from bigtable;",
"select id as groupid, max(age) as groupage from bigtable group by id;",
"select id as groupid, sum(age) as groupage from bigtable group by id;",
"select name, count(*) from bigtable group by name;",
"select /*parallel*/ * from bigtable;",
"update bigtable set age = age + 10;",
"update /*parallel*/ bigtable set age = age + 10;",
"delete from bigtable where id = 20;",
"delete from bigtable_0 where id = 21;",
"delete from bigtable_1 where id = 23;",
"drop table bigtable_0;",
"drop table bigtable_1;",
"drop table bigtable;",
}